QUERY_TOTAL_STUDENTS = """ SELECT COUNT(_) FROM students; """
QUERY_ALL_STUDENT_INFO = """ SELECT * FROM students; """
QUERY_PROBLEMS_SOLVED_GREATER_THAN_50 = """ SELECT * FROM programming WHERE problems_solved > 50; """
QUERY_HIGHEST_MOCK_INTERVIEW_SCORE = """ SELECT MAX(mock_interview_score) FROM placements; """
QUERY_LOWEST_PROBLEMS_SOLVED = """ SELECT MIN(problems_solved) FROM programming; """
QUERY_AVG_PROBLEMS_SOLVED = """ SELECT AVG(problems_solved) FROM programming; """
QUERY_MOCK_INTERVIEW_SCORE_GREATER_THAN_75 = """ SELECT * FROM placements WHERE mock_interview_score > 75; """
QUERY_TOTAL_PROBLEMS_SOLVED = """ SELECT SUM(problems_solved) FROM programming; """
QUERY_STUDENTS_PER_BATCH = """ SELECT course_batch, COUNT(_) FROM students GROUP BY course_batch; """
QUERY_STUDENT_INFO_WITH_PROBLEMS_SOLVED_AND_MOCK_SCORE = """ SELECT s.*, p.problems_solved, pl.mock_interview_score FROM students s JOIN programming p ON s.student_id = p.student_id JOIN placements pl ON s.student_id = pl.student_id;"""